### ISSUE TITLE
Looking for ESCON 24/2 ROS package

### ISSUE THREAD

**Issue by prasuchit** [guzhaoyuan/MaxonEpos2#2]
Hi, I'm fairly new to ROS and I just bought Maxon ESCON 24/2 motor drivers for my project and I'm trying to interface them with ROS. I was wondering if this same package can do that if there are any changes I need to make in this code or there is an entirely different package for that. If so, could you point me in the right direction?

**Comment by guzhaoyuan** [comment]
According to the manual section 1.2
https://www.maxonmotor.com/medias/sys_master/root/8818449776670/466023-ESCON-Module-24-2-Hardware-Reference-En.pdf
I don't think ESCON 24/2 is able to receive digital command at runtime, there is no linux driver and api to communicate with it. Once setup, it seems only read IO inputs to drive servo. So there seems nothing could be done with ros.
